CREATE OR REPLACE TABLE ANALYTICS.FACT_ORDERS AS
SELECT
  o.ORDER_ID,
  o.ORDER_DATE,
  o.CUSTOMER_ID,
  o.PRODUCT_ID,
  o.QUANTITY,
  o.UNIT_PRICE,
  o.LINE_TOTAL,
  o.CHANNEL,
  o.CURRENCY,
  c.COUNTRY,
  p.CATEGORY
FROM ANALYTICS.STG_ORDERS o
LEFT JOIN ANALYTICS.STG_CUSTOMERS c
  ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN ANALYTICS.STG_PRODUCTS p
  ON o.PRODUCT_ID = p.PRODUCT_ID;
