CREATE OR REPLACE VIEW ANALYTICS.STG_ORDERS AS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  PRODUCT_ID,
  ORDER_DATE,
  QUANTITY,
  UNIT_PRICE,
  QUANTITY * UNIT_PRICE AS LINE_TOTAL,
  CHANNEL,
  CURRENCY,
  STATUS
FROM ECOMMERCE_DB.RAW.ORDERS_RAW
WHERE STATUS NOT IN ('CANCELLED', 'REFUNDED');
