
-- Create role, warehouse, database, and schemas for the e-commerce project

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROLE_ECOMMERCE;

GRANT ROLE ROLE_ECOMMERCE TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS WH_ECOMMERCE_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE WH_ECOMMERCE_XS TO ROLE ROLE_ECOMMERCE;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB;
GRANT OWNERSHIP ON DATABASE ECOMMERCE_DB TO ROLE ROLE_ECOMMERCE REVOKE CURRENT GRANTS;

USE ROLE ROLE_ECOMMERCE;
USE DATABASE ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
