USE ROLE ROLE_ECOMMERCE;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_CSV_ECOMMERCE
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL');

CREATE OR REPLACE STAGE ECOMMERCE_STAGE
  URL = 's3://your-ecommerce-bucket/raw/'
  FILE_FORMAT = FF_CSV_ECOMMERCE;

-- In a real environment, you might add storage integration:
-- STORAGE_INTEGRATION = my_integration
