USE ROLE ROLE_ECOMMERCE;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS_RAW (
  CUSTOMER_ID        VARCHAR,
  EMAIL              VARCHAR,
  FIRST_NAME         VARCHAR,
  LAST_NAME          VARCHAR,
  COUNTRY            VARCHAR,
  CREATED_AT         TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PRODUCTS_RAW (
  PRODUCT_ID         VARCHAR,
  SKU                VARCHAR,
  NAME               VARCHAR,
  CATEGORY           VARCHAR,
  UNIT_PRICE         NUMBER(10,2),
  ACTIVE_FLAG        BOOLEAN,
  CREATED_AT         TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ORDERS_RAW (
  ORDER_ID           VARCHAR,
  CUSTOMER_ID        VARCHAR,
  PRODUCT_ID         VARCHAR,
  ORDER_DATE         TIMESTAMP_NTZ,
  QUANTITY           NUMBER(10,0),
  UNIT_PRICE         NUMBER(10,2),
  CHANNEL            VARCHAR, -- 'web', 'mobile', 'store'
  CURRENCY           VARCHAR,
  STATUS             VARCHAR   -- 'PLACED','SHIPPED','CANCELLED','REFUNDED'
);
