USE ROLE ROLE_ECOMMERCE;
USE DATABASE ECOMMERCE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE SNOWPIPE_ORDERS
  AUTO_INGEST = FALSE
AS
  COPY INTO ORDERS_RAW
  FROM @ECOMMERCE_STAGE/orders
  FILE_FORMAT = (FORMAT_NAME = FF_CSV_ECOMMERCE)
  ON_ERROR = 'CONTINUE';

-- For manual testing:
-- ALTER PIPE SNOWPIPE_ORDERS REFRESH;
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME => 'ORDERS_RAW', START_TIME => DATEADD('hour', -1, CURRENT_TIMESTAMP)));
